version: '2'
services:
  elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    image: elasticsearch:5.5.0
    container_name: elasticsearch
    ports:
      - "7200:9200"
      - "7300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elk
  kibana:
    #image: docker.elastic.co/kibana/kibana:5.5.3
    image: kibana:5.5.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk
networks:
  elk:
    driver: bridge
